config updates
mars-protocol/liquidation-helpers pull request #5
Opened 2022-12-26 20:18 UTC by brimigs

2022-12-27 09:55 UTC, grod220 approved these changes

2022-12-27 09:55 UTC, grod220 commented on scripts/deploy/osmosis/config.ts
>  export const osmosisAddresses: Addresses = {
Probably should be `osmosisMainnetAddresses`?

2022-12-27 09:55 UTC, grod220 commented on scripts/deploy/osmosis/index.ts
> +import {osmosisTestnetAddresses, osmosisTestnetConfig} from './config.js'
need to run prettier on these changes

2023-01-31 12:52 UTC, piobab commented
@brimigs is it still valid?

2023-01-31 20:48 UTC, larry0x commented
Merged main into this branch. This should fix the CI.

2023-02-01 09:08 UTC, piobab approved these changes

2023-02-05 15:20 UTC, dancreee requested changes

2023-02-05 15:20 UTC, dancreee commented on scripts/deploy/osmosis/config.ts
> +  rewardCollectorTimeoutSeconds: 60,
I think these reward collector settings should be removed as per red-bank configs?

2023-02-05 15:20 UTC, dancreee commented on scripts/deploy/osmosis/config.ts
> +  multisig: 'osmo1jklpvl3446z5qw58cvq8hqvthzjtsfvs9j65tq',
should be osmo14w4x949nwcrqgfe53pxs3k7x53p0gvlrq34l5n

2023-02-05 15:20 UTC, dancreee commented on scripts/deploy/osmosis/config.ts
> +  multisig: 'osmo1jklpvl3446z5qw58cvq8hqvthzjtsfvs9j65tq',
should be osmo14w4x949nwcrqgfe53pxs3k7x53p0gvlrq34l5n

2023-02-05 15:20 UTC, dancreee commented on scripts/deploy/osmosis/config.ts
> +  channelId: 'TO BE INSERTED AT DEPLOYMENT',
don't think this config needs channel ID?

2023-02-05 15:20 UTC, dancreee commented on scripts/deploy/osmosis/config.ts
> +  marsDenom: 'umars',
not sure if we need mars denom but this is incorrect should be ibc/573FCD90FACEE750F55A8864EF7D38265F07E5A9273FA0E8DAFD39951332B580

2023-02-05 15:20 UTC, dancreee commented on scripts/deploy/osmosis/index.ts
>  import { taskRunner } from '../base'
id rename this file to testnetIndex.ts to be consistent with red bank repo

2023-02-05 15:20 UTC, dancreee commented on scripts/deploy/osmosis/index.ts
>  import { taskRunner } from '../base'
On top of that, I think it would be ideal if we have the multisig address rule here so that as part of the deploy scripts it hands over admin rights to multisig

2023-02-06 02:23 UTC, brimigs commented on scripts/deploy/osmosis/index.ts
>  import { taskRunner } from '../base'
yeah the `deployer.ts` hands over ownership to the multisig at the very end of the script (Line 103). This contract doesn't have 2 step ownership transfer like the red-bank contracts do. 

@piobab - can you please confirm? Do these contracts just have the simple ownership transfer? It looks like its still just executing an update config msg for owner. So no proposing a new owner and accepting proposed needed.

2023-02-06 10:36 UTC, piobab commented on scripts/deploy/osmosis/index.ts
>  import { taskRunner } from '../base'
Ahh yes, right it doesn't have two step ownership. I can update it, should be quick

2023-02-06 15:12 UTC, piobab commented on scripts/deploy/osmosis/index.ts
>  import { taskRunner } from '../base'
@brimigs once this merged you update your deployments https://github.com/mars-protocol/liquidation-helpers/pull/10

2023-02-06 15:45 UTC, piobab commented
@brimigs could you please bump version in Cargo.toml to 1.0.0 ?

2023-02-06 16:14 UTC, brimigs commented on scripts/deploy/osmosis/index.ts
>  import { taskRunner } from '../base'
updated :)

2023-02-06 16:17 UTC, dancreee approved these changes

2023-02-06 16:23 UTC, merged